### ISSUE TITLE
自己尝试了一下,每个平台在Install Qt这一步都报错了

### ISSUE THREAD

**Issue by 384782946** [jaredtao/HelloActions-Qt#1]
![image](https://user-images.githubusercontent.com/11289666/75947575-d570a700-5edb-11ea-94fc-b0dc23f97fc3.png)

**Comment by jaredtao** [comment]
都报错吗？我现在只有android平台报错。python出问题了。其它平台没有问题。

**Comment by 384782946** [comment]
我的所有平台都报错了,都是Install Qt这一步python报的错

**Comment by 384782946** [comment]
今天再执行就通过了,有个疑问,我把workflow里的targetname改成自己qt工程targetname了,执行完成以后,程序包没有发布到release里呀,这个怎么做到持续部署呢?

**Comment by jaredtao** [comment]
install-qt今天更新到2.5.3，全平台可用了。
