### ISSUE TITLE
release包如何上传？

### ISSUE THREAD

**Issue by liangkdm** [jaredtao/HelloActions-Qt#2]
你好，请问一下打包的逻辑
# tag 打包
      - name: package
        if: startsWith(github.event.ref, 'refs/tags/')

我这边已经git push tag 了，还是没有触发打包这个逻辑，请问该怎么处理呢

**Comment by jaredtao** [comment]
创建新tag，push到github，会自动触发的。
有没有可能是前面的步骤出错了，或者别的job出错导致取消了?
tag不触发的情况，我只遇到过一种：以前的tag，删掉，重新打上。

**Comment by liangkdm** [comment]
> 创建新tag，push到github，会自动触发的。
> 有没有可能是前面的步骤出错了，或者别的job出错导致取消了?
> tag不触发的情况，我只遇到过一种：以前的tag，删掉，重新打上。

thanks,tag的确没有打上去，删除重新打上就好了，谢啦
